# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='\u73ed\u53f7')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=255, unique=True, verbose_name='\u73ed\u7ea7\u540d')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('number', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_study.Number')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=255, verbose_name='\u73ed\u7ea7\u540d')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('sex', models.CharField(max_length=2, verbose_name='\u6027\u522b')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_study.Grade', to_field='classname')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('sex', models.CharField(max_length=2, verbose_name='\u6027\u522b')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_study.Grade', to_field='classname')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='stu_teacher', to='model_study.Teacher'),
        ),
    ]
