# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_study', '0003_auto_20180329_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnumber',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='\u73ed\u53f7'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='number',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_study.ClassNumber', to_field='number'),
        ),
    ]
